SET NOCOUNT ON
 
SELECT * INTO #Iso3166 FROM [dbo].[Iso3166] WHERE 1 = 0
 
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AD', N'Andorra')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AE', N'United Arab Emirates')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AF', N'Afghanistan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AG', N'Antigua and Barbuda')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AI', N'Anguilla')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AL', N'Albania')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AM', N'Armenia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AO', N'Angola')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AQ', N'Antarctica')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AR', N'Argentina')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AS', N'American Samoa')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AT', N'Austria')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AU', N'Australia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AW', N'Aruba')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AX', N'Åland Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('AZ', N'Azerbaijan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BA', N'Bosnia and Herzegovina')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BB', N'Barbados')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BD', N'Bangladesh')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BE', N'Belgium')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BF', N'Burkina Faso')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BG', N'Bulgaria')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BH', N'Bahrain')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BI', N'Burundi')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BJ', N'Benin')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BL', N'Saint Barthélemy')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BM', N'Bermuda')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BN', N'Brunei Darussalam')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BO', N'Bolivia, Plurinational State of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BQ', N'Bonaire, Sint Eustatius and Saba')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BR', N'Brazil')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BS', N'Bahamas')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BT', N'Bhutan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BV', N'Bouvet Island')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BW', N'Botswana')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BY', N'Belarus')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('BZ', N'Belize')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CA', N'Canada')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CC', N'Cocos (Keeling) Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CD', N'Congo, the Democratic Republic of the')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CF', N'Central African Republic')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CG', N'Congo')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CH', N'Switzerland')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CI', N'Côte d''Ivoire')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CK', N'Cook Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CL', N'Chile')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CM', N'Cameroon')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CN', N'China')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CO', N'Colombia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CR', N'Costa Rica')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CU', N'Cuba')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CV', N'Cape Verde')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CW', N'Curaçao')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CX', N'Christmas Island')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CY', N'Cyprus')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('CZ', N'Czech Republic')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('DE', N'Germany')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('DJ', N'Djibouti')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('DK', N'Denmark')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('DM', N'Dominica')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('DO', N'Dominican Republic')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('DZ', N'Algeria')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('EC', N'Ecuador')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('EE', N'Estonia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('EG', N'Egypt')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('EH', N'Western Sahara')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ER', N'Eritrea')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ES', N'Spain')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ET', N'Ethiopia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('FI', N'Finland')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('FJ', N'Fiji')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('FK', N'Falkland Islands (Malvinas)')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('FM', N'Micronesia, Federated States of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('FO', N'Faroe Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('FR', N'France')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GA', N'Gabon')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GB', N'United Kingdom')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GD', N'Grenada')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GE', N'Georgia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GF', N'French Guiana')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GG', N'Guernsey')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GH', N'Ghana')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GI', N'Gibraltar')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GL', N'Greenland')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GM', N'Gambia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GN', N'Guinea')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GP', N'Guadeloupe')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GQ', N'Equatorial Guinea')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GR', N'Greece')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GS', N'South Georgia and the South Sandwich Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GT', N'Guatemala')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GU', N'Guam')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GW', N'Guinea-Bissau')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('GY', N'Guyana')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('HK', N'Hong Kong')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('HM', N'Heard Island and McDonald Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('HN', N'Honduras')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('HR', N'Croatia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('HT', N'Haiti')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('HU', N'Hungary')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ID', N'Indonesia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IE', N'Ireland')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IL', N'Israel')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IM', N'Isle of Man')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IN', N'India')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IO', N'British Indian Ocean Territory')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IQ', N'Iraq')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IR', N'Iran, Islamic Republic of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IS', N'Iceland')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('IT', N'Italy')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('JE', N'Jersey')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('JM', N'Jamaica')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('JO', N'Jordan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('JP', N'Japan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KE', N'Kenya')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KG', N'Kyrgyzstan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KH', N'Cambodia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KI', N'Kiribati')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KM', N'Comoros')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KN', N'Saint Kitts and Nevis')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KP', N'Korea, Democratic People''s Republic of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KR', N'Korea, Republic of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KW', N'Kuwait')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KY', N'Cayman Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('KZ', N'Kazakhstan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LA', N'Lao People''s Democratic Republic')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LB', N'Lebanon')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LC', N'Saint Lucia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LI', N'Liechtenstein')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LK', N'Sri Lanka')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LR', N'Liberia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LS', N'Lesotho')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LT', N'Lithuania')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LU', N'Luxembourg')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LV', N'Latvia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('LY', N'Libyan Arab Jamahiriya')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MA', N'Morocco')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MC', N'Monaco')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MD', N'Moldova, Republic of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ME', N'Montenegro')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MF', N'Saint Martin (French part)')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MG', N'Madagascar')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MH', N'Marshall Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MK', N'Macedonia, the former Yugoslav Republic of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ML', N'Mali')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MM', N'Myanmar')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MN', N'Mongolia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MO', N'Macao')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MP', N'Northern Mariana Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MQ', N'Martinique')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MR', N'Mauritania')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MS', N'Montserrat')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MT', N'Malta')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MU', N'Mauritius')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MV', N'Maldives')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MW', N'Malawi')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MX', N'Mexico')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MY', N'Malaysia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('MZ', N'Mozambique')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NA', N'Namibia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NC', N'New Caledonia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NE', N'Niger')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NF', N'Norfolk Island')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NG', N'Nigeria')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NI', N'Nicaragua')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NL', N'Netherlands[note 1]')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NO', N'Norway')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NP', N'Nepal')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NR', N'Nauru')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NU', N'Niue')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('NZ', N'New Zealand')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('OM', N'Oman')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PA', N'Panama')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PE', N'Peru')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PF', N'French Polynesia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PG', N'Papua New Guinea')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PH', N'Philippines')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PK', N'Pakistan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PL', N'Poland')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PM', N'Saint Pierre and Miquelon')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PN', N'Pitcairn')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PR', N'Puerto Rico')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PS', N'Palestinian Territory, Occupied')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PT', N'Portugal')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PW', N'Palau')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('PY', N'Paraguay')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('QA', N'Qatar')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('RE', N'Réunion')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('RO', N'Romania')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('RS', N'Serbia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('RU', N'Russian Federation')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('RW', N'Rwanda')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SA', N'Saudi Arabia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SB', N'Solomon Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SC', N'Seychelles')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SD', N'Sudan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SE', N'Sweden')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SG', N'Singapore')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SH', N'Saint Helena, Ascension and Tristan da Cunha')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SI', N'Slovenia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SJ', N'Svalbard and Jan Mayen')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SK', N'Slovakia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SL', N'Sierra Leone')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SM', N'San Marino')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SN', N'Senegal')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SO', N'Somalia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SR', N'Suriname')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SS', N'South Sudan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ST', N'Sao Tome and Principe')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SV', N'El Salvador')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SX', N'Sint Maarten')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SY', N'Syrian Arab Republic')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('SZ', N'Swaziland')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TC', N'Turks and Caicos Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TD', N'Chad')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TF', N'French Southern Territories')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TG', N'Togo')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TH', N'Thailand')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TJ', N'Tajikistan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TK', N'Tokelau')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TL', N'Timor-Leste')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TM', N'Turkmenistan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TN', N'Tunisia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TO', N'Tonga')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TR', N'Turkey')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TT', N'Trinidad and Tobago')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TV', N'Tuvalu')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TW', N'Taiwan, Province of China')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('TZ', N'Tanzania, United Republic of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('UA', N'Ukraine')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('UG', N'Uganda')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('UM', N'United States Minor Outlying Islands')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('US', N'United States')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('UY', N'Uruguay')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('UZ', N'Uzbekistan')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('VA', N'Holy See (Vatican City State)')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('VC', N'Saint Vincent and the Grenadines')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('VE', N'Venezuela, Bolivarian Republic of')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('VG', N'Virgin Islands, British')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('VI', N'Virgin Islands, U.S.')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('VN', N'Viet Nam')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('VU', N'Vanuatu')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('WF', N'Wallis and Futuna')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('WS', N'Samoa')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('XX', N'**Other/Unknown**')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('YE', N'Yemen')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('YT', N'Mayotte')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ZA', N'South Africa')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ZM', N'Zambia')
INSERT #Iso3166 ([CountryId], [CountryTitle])
VALUES ('ZW', N'Zimbabwe')
 
UPDATE t1
SET t1.CountryTitle = t2.CountryTitle
FROM dbo.Iso3166 t1 
JOIN #Iso3166 t2 
ON t1.CountryId = t2.CountryId
 
INSERT dbo.Iso3166 (CountryId, CountryTitle)
SELECT t1.CountryId, t1.CountryTitle
FROM #Iso3166 t1 
LEFT JOIN dbo.Iso3166 t2
ON  t1.CountryId = t2.CountryId
WHERE t2.CountryId IS NULL 
 
DROP TABLE #Iso3166
