//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareItsMade.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Commoditys = new HashSet<Commodity>();
        }
    
        public string ClassId { get; set; }
        public string ClassTitle { get; set; }
        public string FamilyId { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual ICollection<Commodity> Commoditys { get; set; }
    }
}
