//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareItsMade.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        public string CommodityId { get; set; }
        public string CommodityTitle { get; set; }
        public string ClassId { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
