//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareItsMade.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public Family()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public string FamilyId { get; set; }
        public string FamilyTitle { get; set; }
        public string SegmentId { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual Segment Segment { get; set; }
    }
}
