//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareItsMade.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iso3166
    {
        public Iso3166()
        {
            this.Iso3166_2 = new HashSet<Iso3166_2>();
        }
    
        public string CountryId { get; set; }
        public string CountryTitle { get; set; }
    
        public virtual ICollection<Iso3166_2> Iso3166_2 { get; set; }
    }
}
