//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareItsMade.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iso3166_2
    {
        public string SubdivisionId { get; set; }
        public string CountryId { get; set; }
        public string SubdivisionTitle { get; set; }
    
        public virtual Iso3166 Iso3166 { get; set; }
    }
}
