//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareItsMade.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public Segment()
        {
            this.Familys = new HashSet<Family>();
        }
    
        public string SegmentId { get; set; }
        public string SegmentTitle { get; set; }
    
        public virtual ICollection<Family> Familys { get; set; }
    }
}
